name: Check MongoDB Server

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check-mongodb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo

    - name: Check MongoDB server
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        python -c "import pymongo; client = pymongo.MongoClient('${{ secrets.MONGODB_URI }}'); client.server_info()"
